In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
list1 = [2,3,4,5,6]
type(list1)

list

In [3]:
array = np.array([2,3,4,5,6])
type(array)

numpy.ndarray

# ndim: to check the dimensions of an array

In [4]:
array.ndim

1

In [5]:
a=[1,2,5,3,4,5]
b=['a','b','c','d','e','f']

import pandas as pd
df=pd.DataFrame(zip(a,b))
df

0  1
0  1  a
1  2  b
2  5  c
3  3  d
4  4  e
5  5  f

In [6]:
array = np.array([[2,3,4,5,6]])
array.ndim

2

In [7]:
array = np.array([[2,3,4,5,6],
                  [5,6,7,8,9]])
array.ndim

2

In [8]:
array = np.array([[[2,3],
                   [5,6]],
                  [[1,1],
                   [1,1]]])
array.ndim

3

In [9]:
array = np.array([[[2,3],[5,6]],[[1,1],[1,1]]])
array.ndim

3

In [10]:
array = np.array(2.3)
array.ndim

0

# ndmin : converting lower dimensions into higher dimensions

In [11]:
array = np.array(2.3,ndmin=3)
print(array)
array.ndim

[[[2.3]]]


3

In [12]:
array = np.array([[[2,3],[3,4]]],ndmin=1)
print(array)
array.ndim

[[[2 3]
  [3 4]]]


3

# converting a list to an array

In [13]:
l1 = [2,3,4]
arr = np.array(l1)
arr

array([2, 3, 4])

In [14]:
l1 = 2,3,4
arr = np.array(l1)
arr

array([2, 3, 4])

In [15]:
l1 = (2,3,4)
arr = np.array(l1)
arr

array([2, 3, 4])

In [16]:
l1 = 'string'
arr = np.array(l1)
arr

array('string', dtype='<U6')

In [17]:
l1 = set((2,3,4))
arr = np.array(l1)
arr

array({2, 3, 4}, dtype=object)

# why is numpy called as homogeneous data type

In [ ]:
array = np.array([2,3.0,5])
array

In [2]:
import numpy as np
array = np.array([2,3.0,3+4j])
array

array([2.+0.j, 3.+0.j, 3.+4.j])

# dtype : Assigning a single data type to an entire array

In [3]:
array = np.array([2,3.1,5],dtype='int')
array

array([2, 3, 5])

In [4]:
array = np.array([2,3.1,5],dtype='float')
array

array([2. , 3.1, 5. ])

In [5]:
array = np.array([2,3.1,'5'],dtype='object')
array

array([2, 3.1, '5'], dtype=object)

# Indexing

In [6]:
array = np.array([2,3,5,6])
array

array([2, 3, 5, 6])

In [7]:
array[-1]

6

In [8]:
array[1]

3

In [9]:
array = np.array([[[2,3,5,6],
                   [5,6,7,8],
                   [4,5,5,5]],
                  [[8,8,9,0],
                   [1,2,3,1],
                   [2,2,3,1]]])
array

array([[[2, 3, 5, 6],
        [5, 6, 7, 8],
        [4, 5, 5, 5]],

       [[8, 8, 9, 0],
        [1, 2, 3, 1],
        [2, 2, 3, 1]]])

In [10]:
array[1][2][-2]

3

# Slicing

## Symmetric Slicing

In [11]:
array[1][2][1:3]

array([2, 3])

In [12]:
array = np.array([[[2,3,5,6],
                   [5,6,7,8],
                   [4,5,5,5]],
                  [[8,8,9,0],
                   [1,2,3,1],
                   [2,2,3,1]]])
print(array[1])


array[1][:2,1:3]  #we do the slicing of rows before the comma & that of the columns after the comma

[[8 8 9 0]
 [1 2 3 1]
 [2 2 3 1]]


array([[8, 9],
       [2, 3]])

In [13]:
array[:,:2,1:3]

array([[[3, 5],
        [6, 7]],

       [[8, 9],
        [2, 3]]])

In [14]:
array = np.array([[[[2,3,5,6],
                    [5,6,7,8],
                    [4,5,5,5]],
                   [[8,8,9,0],
                    [1,2,3,1],
                    [2,2,3,1]]],
                  
                  [[[2,3,5,6],
                    [5,6,7,8],
                    [4,5,5,5]],
                   [[8,8,9,0],
                    [1,2,3,1],
                    [2,2,3,1]]]])

array[:,:,1:,2:]
# array[:,:,1:2,2:]
array[:,:1,1:,:2]

array([[[[5, 6],
         [4, 5]]],


       [[[5, 6],
         [4, 5]]]])

## Asymmetric Slicing

In [15]:
array = np.array([[[2,3,5,6],
                   [5,6,7,8],
                   [4,5,5,5]],
                  [[8,8,9,0],
                   [1,2,3,1],
                   [2,2,3,1]]])
array

array([[[2, 3, 5, 6],
        [5, 6, 7, 8],
        [4, 5, 5, 5]],

       [[8, 8, 9, 0],
        [1, 2, 3, 1],
        [2, 2, 3, 1]]])

In [16]:
a = array[:1,1:,1:]
print(a)
b = array[1:,:2,:3]
print(b)

x = np.concatenate([a,b])
x

[[[6 7 8]
  [5 5 5]]]
[[[8 8 9]
  [1 2 3]]]


array([[[6, 7, 8],
        [5, 5, 5]],

       [[8, 8, 9],
        [1, 2, 3]]])

In [17]:
a = [[1, 2, 3],[10, 20, 30]]
b = [[100,200,300]]
a = np.array(a) 
b = np.array(b) 
print(a)
print(b)

c = np.concatenate([a,b])
c


[[ 1  2  3]
 [10 20 30]]
[[100 200 300]]


array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])